version: '3.9'
services:
  mysql:
    image: mysql:8
    container_name: mysql-estoque
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: suasenha
      MYSQL_DATABASE: estoque_db
      MYSQL_USER: estoque_user
      MYSQL_PASSWORD: estoque_pass
	  ports:
	    - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
